[package]
name = "app"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures-util = "0.3.30"
libc = "0.2.153"
mio = "0.8.10"
rocket = "=0.5.0-rc.4"
