name: Backend CICD Github actions.

on: [push]

jobs:
    create-docker-image-ci:
        runs-on: ubuntu-latest
        steps:
            - name: Test CI
              run: echo "Test CI"

            # - name: Checkout Repository
            #   uses: actions/checkout@v3

            - name: Test CI
              run: podman --version

            # - name: Pull rust image.
            #   run: podman pull rust

            # - name: Create docker image from current directory.
            #   run: podman build --tag lesenii:dev1.0.0 .

            # - name: List docker images.
            #   run: podman images

            - name: Podman Operations
            run: |
              podman --version
              podman pull rust
              podman build --tag lesenii:dev1.0.0 .
              podman images

